# Generated by Django 4.2.6 on 2023-11-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='note',
        ),
        migrations.AddField(
            model_name='notes',
            name='content',
            field=models.TextField(default='Enter your note here...'),
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default='empty', max_length=200),
            preserve_default=False,
        ),
    ]
